server:
  port: 8090
  forward-headers-strategy: framework

#spring:
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#  datasource:
#    hikari:
#      jdbc-url: jdbc:h2:mem:springcoredb
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    properties:
#      hibernate:
#        format_sql: true
#        show_sql: true
#        dialect: org.hibernate.dialect.H2Dialect
#    hibernate:
#      ddl-auto: create

spring:
  datasource:
    url: jdbc:postgresql://112.172.238.137:5432/ghostvilage
    username: whitewise
    password: qwerpoiu12@@
  thymeleaf:
    cache: false
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace

springdoc:
  swagger-ui:
    disable-swagger-default-url: true   #디폴트 페이지 안나오게